// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxjq5t-Bc8thCTMGOyl1YUY6mGM62HQNo',
    appId: '1:40006167911:web:629722458edc41f336d3c2',
    messagingSenderId: '40006167911',
    projectId: 'decisiondiary-50b08',
    authDomain: 'decisiondiary-50b08.firebaseapp.com',
    storageBucket: 'decisiondiary-50b08.firebasestorage.app',
    measurementId: 'G-SGKVCQVLP8',
    databaseURL: 'https://decisiondiary-50b08-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZQlivGCkTtcM1WUtF2ovaYumH6tiLoEk',
    appId: '1:40006167911:android:4c96f6fe9a5ad72836d3c2',
    messagingSenderId: '40006167911',
    projectId: 'decisiondiary-50b08',
    storageBucket: 'decisiondiary-50b08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwbYGVNBYv1xlb1VTXzYYZA1xYBZbzMlg',
    appId: '1:40006167911:ios:e6ab4c5180912de236d3c2',
    messagingSenderId: '40006167911',
    projectId: 'decisiondiary-50b08',
    storageBucket: 'decisiondiary-50b08.firebasestorage.app',
    iosBundleId: 'com.example.decisiondiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwbYGVNBYv1xlb1VTXzYYZA1xYBZbzMlg',
    appId: '1:40006167911:ios:e6ab4c5180912de236d3c2',
    messagingSenderId: '40006167911',
    projectId: 'decisiondiary-50b08',
    storageBucket: 'decisiondiary-50b08.firebasestorage.app',
    iosBundleId: 'com.example.decisiondiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxjq5t-Bc8thCTMGOyl1YUY6mGM62HQNo',
    appId: '1:40006167911:web:d99fc4bae46373b136d3c2',
    messagingSenderId: '40006167911',
    projectId: 'decisiondiary-50b08',
    authDomain: 'decisiondiary-50b08.firebaseapp.com',
    storageBucket: 'decisiondiary-50b08.firebasestorage.app',
    measurementId: 'G-26BTYE8ECC',
  );
}
